name: github pages

# masterブランチにプッシュしたときjobsに記述した操作を行う
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    # ubuntu OS を仮想マシン上に用意する
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # Node.js環境のセットアップを行う
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      # npm install の際にキャッシュを使うよう設定
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # package.jsonに基づき依存パッケージをインストールする
      - name: install
        run: yarn install --frozen-lockfile

      - name: add nojekyll
        run: touch ./out/.nojekyll

      # gh-pagesブランチにoutディレクトリの中身をプッシュする
      # gh-pagesブランチは自動的に作成される
      - name: deploy
        run: yarn run publish
